---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - organization.prototypes.com
  resources:
  - virtualclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - organization.prototypes.com
  resources:
  - virtualclusters/finalizers
  verbs:
  - update
- apiGroups:
  - organization.prototypes.com
  resources:
  - virtualclusters/status
  verbs:
  - get
  - patch
  - update
