apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtualmachine-reader-binding
subjects:
- kind: ServiceAccount
  name: src-controller-manager
  namespace: src-system
roleRef:
  kind: ClusterRole
  name: virtualmachine-reader
  apiGroup: rbac.authorization.k8s.io